name: libdispatch Windows clang

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      run: cmake --preset windows-release

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}\out\build\windows-release

    - name: Install
      run: cmake --install ${{github.workspace}}\out\build\windows-release

    - name: Upload artifact windows-release-${{ steps.vars.outputs.sha_short }}.zip
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v1
      with:
        name: windows-release-${{ steps.vars.outputs.sha_short }}
        path: ./out
